color = input ("What is your favorite color?")
print(color)
print("is your favorite color")
name = input ("What is your name?")
print(name,)
print("a heroic name indeed!")
quest = input ("Now, what is your Quest?")
print(quest)
print("Goodluck!")